<?php

namespace Tests\Feature;

use App\Reply;
use App\Thread;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class ThreadsTest extends TestCase
{
    
    use DatabaseMigrations;
    
    public $thread;
    
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        
        $this->thread = factory(Thread::class)->create();
        
    }
    
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testExample()
    {
        $response = $this->get('/');
        
        $response->assertStatus(200);
    }
    
    public function test_a_user_can_view_threads()
    {
        
        $this->get('/threads')
             ->assertStatus(200)
             ->assertSee($this->thread->title);
    }
    
    public function test_a_user_can_view_single_thread()
    {
        
        $this->get('/threads/'.$this->thread->id)
             ->assertStatus(200)->assertSee($this->thread->title);
    }
    
    public function test_a_user_can_read_replies_associated_with_a_thread()
    {
        $reply = factory(Reply::class)
            ->create(['thread_id' => $this->thread->id]);
        
        $this->get('/threads/'.$this->thread->id)
             ->assertSee($reply->body);
    }
    
    public function test_an_auth_user_can_create_thread()
    {
        $this->withoutExceptionHandling();
        //Given a signed in user
        $user = factory('App\User')->create();
        $this->be($user);
        //Create a thread
        $thread = factory('App\Thread')->make(['user_id' => auth()->id()]);
        
        $this->post('/threads', $thread->toArray());
        //Visible in the thread page
        $this->get('/threads')
             ->assertSee($thread->title)
             ->assertSee($thread->body);
    }
    
    public function test_guest_may_not_create_thread(){
        $this->withoutExceptionHandling();
        $thread = factory('App\Thread')->make();
        $this->post('/threads', $thread->toArray());
    }
    
}
